- name: Holz&bull;Arbeiten
  link: wood
  description: Ich fertige Holzarbeiten jenseits der Norm. Meine Liebe zur Seele des Holzes und meine Passion für altbewährte Handwerkstechniken fließen in jedes Werkstück mit ein.
  image: assets/images/Brunnendeckel_geschlossen1.JPG
- name: Baum&bull;Kontrolle
  link: tree
  description: Bäume erhalten, Sicherheit gewährleisten!
  image: assets/images/IMG_2170.JPG
#- name: Wald&bull;Dienstleistungen
#  link: walddienstleistungen
#  description: Keine
#  image: /assets/images/DSC_5210.JPG
#- name: Andere
#  link: andere
#  description: Keine
#  image: /assets/images/IMGP8893.JPG
